title: DREAM MOTORS LIMITED
baseURL: /
params:
  palette: blue
  header:
    title: DREAM MOTORS LIMITED
    logo_img: /images/unnamed-1-1-.jpg
    has_nav: true
    nav_links:
      - label: Welcome
        url: Welcome to Dream Motors Limited, your number one source for all things,
          Newly Imported Vehicles, Quality Used Parts and Car Rental Services.
          We aim to provide the best possible service for our customers.
        new_window: false
      - label: Cars For Sale
        url: "2018 Honda Fit "
        primary: true
        new_window: true
      - label: Rental Cars Available
        url: 2012 Subaru Impreza
        new_window: true
      - label: Used Parts Available
        url: Parts available for vehicles 2004 and Up
        new_window: true
  footer:
    subscribe_title: Send us an email
    subscribe_content: dreamsales44@gmail.com
    has_subscribe: true
    social_title: Community
    social_links:
      - label: Instagram
        url: https://www.instagram.com/dreammotorslimited/
        new_window: true
      - new_window: true
        label: Facebook
        url: https://www.facebook.com/DREAMMOTORSLTD
        primary: true
    tagline: DREAM MOTORS LIMITED
    logo_img: /images/unnamed-1-1-.jpg
    has_social: true
    content: ""
    links:
      - label: Made with Stackbit
        url: https://www.stackbit.com
        new_window: true
    nav_title: DREAM MOTORS LIMITED
    nav_links:
      - label: About Us
        url: /about
        new_window: true
      - label: Request a quote
        url: signup
      - label: Contact
        url: (876) 822-0850 , (876) 397-5756
    has_nav: true
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
