title: DREAM MOTORS LIMITED
baseURL: /
params:
  palette: blue
  header:
    title: DREAM MOTORS LIMITED
    logo_img: /images/unnamed-1-1-.jpg
    has_nav: true
    nav_links:
      - label: Welcome
        url: /welcome
        new_window: true
      - label: Cars For Sale
        url: /features
        primary: true
        new_window: true
      - label: Rental Cars Available
        url: /pricing
        new_window: true
      - label: Used Parts Available
        url: /style-guide
        new_window: true
  footer:
    subscribe_title: Send us an email
    subscribe_content: dreamsales44@gmail.com
    has_subscribe: true
    social_title: Community
    social_links:
      - label: Instagram
        url: https://www.instagram.com/dreammotorslimited/
        new_window: true
      - new_window: true
        label: Facebook
        url: https://www.facebook.com/DREAMMOTORSLTD
        primary: true
    tagline: DREAM MOTORS LIMITED
    logo_img: /images/unnamed-1-1-.jpg
    has_social: true
    content: ""
    links:
      - label: Made with Stackbit
        url: https://www.stackbit.com
        new_window: true
    nav_title: DREAM MOTORS LIMITED
    nav_links:
      - label: About Us
        url: /about
        new_window: true
      - label: Request a quote
        url: /Quote
        new_window: true
      - label: Contact
        url: /contact
    has_nav: true
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
