title: DREAM MOTORS LIMITED
baseURL: /
params:
  palette: blue
  header:
    title: DREAM MOTORS LIMITED
    logo_img: /images/unnamed-1-1-.jpg
    has_nav: true
    nav_links:
      - label: Home
        url: /
      - label: CARS FOR SALE
        url: /features
        primary: true
        new_window: false
      - label: RENTAL CARS AVAILABLE
        url: /pricing
      - label: USED PARTS AVAILABLE
        url: /style-guide
      - label: Sign Up
        url: /signup
        primary: true
  footer:
    subscribe_title: Subscribe
    subscribe_content: Stay up to date with our latest developments.
    has_subscribe: true
    social_title: Community
    social_links:
      - label: Instagram
        url: https://www.instagram.com/dreammotorslimited/
        new_window: true
      - label: LinkedIn
        url: https://www.linkedin.com/
        new_window: true
    tagline: DREAM MOTORS LIMITED
    logo_img: /images/unnamed-1-1-.jpg
    has_social: true
    content: "&copy; Stackbit. All rights reserved."
    links:
      - label: Made with Stackbit
        url: https://www.stackbit.com
        new_window: true
    nav_title: DREAM MOTORS LIMITED
    nav_links:
      - label: About Us
        url: "Welcome to Dream Motors Limited, your number one source for all things,
          Newly Imported Vehicles, Used Japanese Auto Parts, and Car Rental
          Services. We're dedicated to providing you the very best of Quality
          Pre-Owned Vehicles with an emphasis on Used genuine auto parts, Car
          Rentals, Auto body repairs, and paintwork.   Founded in 2011 by Nigel
          Gordon, Dream Motors Limited has come a long way from its beginnings
          at 86A Molynes Road. When Nigel Gordon first started out, his passion
          for Quality Pre-Owned Vehicles and Used Genuine Japanese Auto Parts
          drove him to start his own business. Dream Motors Limited began its
          operation with a small staff consisting of three persons, Mr. Nigel
          Gordon, his secretary Monique Hudson and his bearer and handyman Mr.
          Barris Williams. The steady growth resulted in the expansion to
          another location in 2015 which was 44 Molynes Road, It was then Mr.
          Nigel Gordon decided to add Auto body repairs and paintwork to the
          company's services.    In 2017 Dream Motors Limited relocated to 3
          Clarendon place, where its operation continued. Dream Motors Limited
          offers the services of the sale of Quality Pre-Owned vehicles, Used
          genuine Japanese auto parts, car rental services, autobody repairs,
          and paintwork. "
      - label: Blog
        url: /blog
      - label: Request a quote
        url: signup
      - label: Contact
        url: (876) 822-0850 , (876) 397-5756
    has_nav: true
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
